{create: 'query_db', group: [{ruins: ['filename', 'datatime', 'feature_name'], index: ['category', 'feature_name', 'loc']}, 'addr']};
{upset: 'ruins', vertex: [['v1', {filename: '破旧小屋.jpg', datatime: 0d1653446732, feature_name: [0, 0]}], ['v2', {category: 'HDR', filename: '夕阳.jpg', datatime: 0d1653446732}], ['v3', {category: '赛博朋克', filename: '阿丽塔.jpg', datatime: 0d1653446732}]]};
{upset: 'ruins', vertex: [['v4', {filename: '垃圾堆.jpg', datatime: 0d1653315732, feature_name: [0, 0.5]}], ['v5', {category: 'HDR', filename: '海岸线.jpg', datatime: 0d1653315732}], ['v6', {category: '赛博朋克', filename: '机械姬.jpg', datatime: 0d1653315732}]]};
{upset: 'ruins', vertex: [['v7', {filename: '危楼.jpg', datatime: 0d1653105732, feature_name: [0, 1]}], ['v8', {category: 'HDR', filename: '山崖.jpg', datatime: 0d1653105732, feature_name: [0.5, 0]}], ['v9', {category: '赛博朋克', filename: '2022.jpg', datatime: 0d1653105732}]]};
{upset: 'ruins', vertex: [['v7', {filename: '破墙.jpg', datatime: 0d1651105732, feature_name: [0, 1.5]}], ['v8', {category: 'HDR', filename: '蓝天.jpg', datatime: 0d1651105732, feature_name: [0.5, 0]}], ['v9', {category: '赛博朋克', filename: '大佐.jpg', datatime: 0d1651105732}]]};
{upset: 'ruins', vertex: [['1', {filename: '破墙0.jpg', datatime: 0d5}]]};
{upset: 'ruins', vertex: ['3', '4', '5']};
{upset: 'ruins', vertex: [[1, {filename: '破墙0.jpg', datatime: 0d1651105732}]]};
{upset: 'addr', vertex: [[1, {filename: '破墙1.jpg', datatime: 0d1651105732}]]};
{upset: 'addr', vertex: [[2, {filename: '破墙2.jpg', loc: [131.24194, 37.12532]}]]};
{upset: 'addr', vertex: [3, 4, 5]};
ast {query: 'ruins', in: 'vertex_db', where: {category: '废墟'}};
{query: 'ruins'};
{query: 'ruins', in: 'vertex_db', where: {category: '废墟'}};
{query: 'ruins', in: 'query_db', where: {category: '赛博朋克'}};
ast {query: 'ruins', in: 'vertex_db', where: {datatime: {$lt: 1653315732}}};
{query: 'ruins', in: 'query_db', where: {datatime: {$lt: 0d1653315732}}};
{query: 'ruins', in: 'query_db', where: {datatime: {$gt: 0d1653315732}}};
{query: 'ruins', in: 'query_db', where: {datatime: {$gte: 0d1653315732}}};
{query: 'ruins', in: 'query_db', where: {datatime: {$lte: 0d1653446731}}};
{remove: 'ruins', vertex: ['3']};
{dump: 'query_db'};
{drop: 'query_db'};
