{create: 'edge_test'}
{upset: 'edge_test', vertex: [['v1', {color: '#343e58', location: [131.24194, 37.12532], create_time: 1}], ['v2', {color: '#343e58', keyword: ['a', 'b'], create_time: 1}],['v3', {text: b64'5Zyo57q/57yW56CB6Kej56CB', keyword: ['a'], create_time: 3}], ['v11']]}
{upset: 'edge_test', vertex: [['v4', {color: '#000000', location: [131.24194, inf], create_time: 1}], ['v5', {color: '#ffffff', keyword: [], create_time: -1}],['v6', {text: b64'5Zyo57q/57yW56CB6Kej56CB', keyword: ['a'], create_time: 1646321609}], ['v13']]}
{upset: 'edge_test', edge: [ ['v1', --, 'v2'], ['v2', ->, 'v3'], ['v3', ->, 'v3'], ['v4'] ] }
{upset: 'edge_test', edge: [ ['v5', --, 'v2'], ['v6', ->, 'v3'], ['v13', ->, 'v1'], ['v11'] ] }
{query: vertex, in: 'edge_test'}
{query: vertex, in: 'edge_test', where: {keyword: 'b'}}
{query: vertex, in: 'edge_test', where: {id: 'v1', ->: 1}}
{drop: 'edge_test'}
