name: andriod

on:
  push:
    branches: [ master, ci-* ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-11
    strategy:
      platform:
        arch: ['armeabi-v7a', 'x86', 'x86_64']

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: third_party
        run: |
          cd ${{github.workspace}}/third_party/libmdbx
          git fetch --tags --prune --force
          git branch
          cd ${{github.workspace}}/third_party/fmt
          git fetch --tags --prune --force
          git branch
          cd ${{github.workspace}}/third_party/eigen
          git fetch --tags --prune --force
          git branch
          cd ${{github.workspace}}
          git submodule foreach 'git fetch --tags --prune --force; git fetch origin; git checkout $(git describe --tags `git rev-list --tags --max-count=1`);'
      - name: Android NDK toolchain Setup
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with: 
          ndk-version: r25
          add-to-path: false
      - name: update flex/bison
        run: |
          brew install bison
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
      - name: Configure And Build
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          cmake -B ${{github.workspace}}/build/x86_64 -DCMAKE_TOOLCHAIN_FILE=${{env.ANDROID_NDK_HOME}}/build/cmake/android.toolchain.cmake -DANDROID_NDK=${{env.ANDROID_NDK_HOME}} -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-19 -DANDROID_STL=c++_shared -DGQLITE_BUILD_TEST=TRUE
          cmake --build ${{github.workspace}}/build/x86_64 --config ${{env.BUILD_TYPE}}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_2
          sdcard-path-or-size: 100M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: chmod +x ${{github.workspace}}/test/android.sh && ${{github.workspace}}/test/android.sh