name: andriod

on:
  push:
    branches: [ master, ci-* ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: third_party
      run: |
        cd ${{github.workspace}}/third_party/libmdbx
        git fetch --tags --prune --force
        git branch
        cd ${{github.workspace}}/third_party/fmt
        git fetch --tags --prune --force
        git branch
        cd ${{github.workspace}}/third_party/eigen
        git fetch --tags --prune --force
        git branch
        cd ${{github.workspace}}
        git submodule foreach 'git fetch --tags --prune --force; git fetch origin; git checkout $(git describe --tags `git rev-list --tags --max-count=1`);'
    - name: Android NDK toolchain Setup
      uses: ravinderjangra/android-ndk-toolchain-setup@0.1
      with: 
        api: '21'
        arch: 'arm'
        install-location: 'toolchains'
    - name: Build
      # Build your program with the given configuration
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=toolchains/build/cmake/android.toolchain.cmake -DANDROID_NDK=toolchains -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-19 -DANDROID_STL=c++_shared -DGQLITE_BUILD_TEST=TRUE
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        target: default
        arch: x86
        profile: Nexus 6
        script: ./gradlew connectedCheck --stacktrace
    
